# **100 NumPy Exercises**

**1. Import the numpy package under the name np**

In [1]:
import numpy as np

<br><br>
**2. Print the numpy version and the configuration**

In [57]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


<br><br>
**3. Create a null vector of size 10**

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<br><br>
**4. How to find the memory of any array size**

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])

print(a.size * a.itemsize, "bytes")

48 bytes


<br><br>
**5. How to get the documentation of the numpy add function from the command line?**

In [11]:
help(np.add)    # np.add?

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

<br><br>
**6. Create a null vector of size 10 but the fifth value which is 1**

In [12]:
null_array = np.zeros(10)
null_array[4] = 1
null_array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

<br><br>
**7. Create a vector with values ranging from 10 to 49**

In [13]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

<br><br>
**8. Reverse a vector (first element becomes last)**

In [58]:
a = np.arange(10)
print("a:", a)
b = a[::-1]
print("b:", b)

a: [0 1 2 3 4 5 6 7 8 9]
b: [9 8 7 6 5 4 3 2 1 0]


<br><br>
**9. Create a 3X3 matrix with values ranging from 0 to 8**

In [59]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<br><br>
**10. Find indices of non-zero elements from \[1, 2, 0, 0, 4, 0\]**

In [61]:
# My first approach
my_list = np.array([1, 2, 0, 0, 4, 0])
print(np.where(my_list != 0))

# Second approach (better approach)
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4]),)
(array([0, 1, 4]),)


<br><br>
**11. Create a 3X3 identity matrix**

In [45]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<br><br>
**12. Create a 3x3x3 array with random values**

In [67]:
# First approach
print("First:", np.random.random(27).reshape(3, 3, 3), sep = "\n")

# Second approrach
print("\nSecond:", np.random.random((3, 3, 3)), sep = "\n")

First:
[[[0.31180094 0.76902631 0.15992744]
  [0.38015128 0.96063063 0.19086115]
  [0.90208944 0.51419093 0.09986331]]

 [[0.13207861 0.53532195 0.94692288]
  [0.63998149 0.40074566 0.50727587]
  [0.92481181 0.3901461  0.56887901]]

 [[0.58059977 0.35420787 0.78793575]
  [0.19997606 0.63940674 0.68521915]
  [0.27027342 0.10231732 0.92286036]]]

Second:
[[[0.84986084 0.63537653 0.55497935]
  [0.30746476 0.72979939 0.8509643 ]
  [0.82625781 0.19323847 0.9429851 ]]

 [[0.1722983  0.64256412 0.39560428]
  [0.60937098 0.88264907 0.24668152]
  [0.30073906 0.39232215 0.24747531]]

 [[0.40384569 0.20563774 0.21810007]
  [0.60599349 0.43087069 0.96017514]
  [0.95611299 0.86023235 0.17851564]]]


<br><br>
**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [68]:
random_matrix = np.random.random((10,10))
print("Max:", random_matrix.max(), "\tMin:", random_matrix.min())

Max: 0.9915953541963721 	Min: 0.011479908886804169


<br><br>
**14. Create a random vector of size and find the mean value**

In [56]:
np.random.random(30).mean()

0.4997230244303746

<br><br>
**15. Create a 2d array with 1 on the border and 0 inside**

<br><br>
**16. How to add a border (filled with 0's) around an existing array?**