# **NumPy: the absolute basics for beginners**
## **Session 2**

In [70]:
# Imports the numpy library as an alias 'np'
import numpy as np

## **What is an array?**

In [71]:
# Initializing numpy array using python list
a = np.array([1, 2, 3, 4, 5, 6])
# or
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Printing the array using indexing
print(b[0])

[1 2 3 4]


<br><br>
## **More information about arrays**
This section covers *1D array, 2D array, ndarray, vector, matrix*

<br><br>
### **How to create a basic array**
This section covers *np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype*

In [72]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [73]:
np.zeros(2)

array([0., 0.])

In [74]:
np.ones(4)

array([1., 1., 1., 1.])

In [75]:
# Create an empty array with 3 elements
np.empty(3)

array([0.e+000, 5.e-324, 1.e-323])

In [76]:
np.arange(4)

array([0, 1, 2, 3])

In [77]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [78]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**Specifying your data type**

In [79]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

<br><br>
## **Adding, removing, and sorting elements**
This section covers *np.sort(), np.concatenate()*

In [80]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [81]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

np.concatenate((x, y), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

<br><br>
## **How do you know the shape and size of an array?**
This section covers *ndarray.ndim, ndarray.size, ndarray.shape*

In [84]:
array = np.arange(3)
array.shape

(3,)

In [85]:
help(np.newaxis)

Help on NoneType object:

class NoneType(object)
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.



In [86]:
example = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
b = np.nonzero(example < 5)
b[0]

array([0, 0, 0, 0])

In [88]:
list_of_coordinates = list(zip(b[0], b[1]))
list_of_coordinates

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [89]:
list(zip(a, b))

[(1, array([0, 0, 0, 0])), (2, array([0, 1, 2, 3]))]

In [92]:
example[1, 1]

6