<a href="https://colab.research.google.com/github/Nischal2015/Python/blob/main/NumPy_Practise_Sessions/Session1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python NumPy**
## **Session 1**<br><br> 


In [1]:
# Importing the numpy library
import numpy as np

<br><br> 
## **2. How to create a NumPy array?**

This section contains various ways to create a numpy array as well as some of the operations that can be performed with numpy array.

In [2]:
# Create an 1d array from a list
list1 = [0, 1, 2, 3, 4]
arr1d = np.array(list1)

# Print the array and its type
print(type(arr1d))
arr1d

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

In [3]:
# list1 + 2    # This results in an error

# Add 2 to each element of arr1d
# Addition like operation
arr1d + 2

array([2, 3, 4, 5, 6])

In [4]:
# Create a 2d array from a list of lists
list2 = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
arr2d = np.array(list2)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# Create a float 2d array
# Using only 'float' as dtype is deprecated
arr2d_f = np.array(list2, dtype = float)    # By default NumPy creates 64 bit float
arr2d_f

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [6]:
# Convert to int data type
arr2d_f.astype(int)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# Convert to int then to string
arr2d_f.astype(int).astype(str)

array([['0', '1', '2'],
       ['3', '4', '5'],
       ['6', '7', '8']], dtype='<U21')

In [8]:
# Create a boolean array
arr2d_b = np.array([1, 0, 12, 23], dtype = bool)
arr2d_b

array([ True, False,  True,  True])

In [9]:
# Create an object array to hold numbers as well as strings
arr1d_obj = np.array([2, 'Nischal', 3.1415])
arr1d_obj

array(['2', 'Nischal', '3.1415'], dtype='<U21')

In [10]:
# Convert an array back to list
arr1d_obj.tolist()

['2', 'Nischal', '3.1415']

<br><br>
## **3. How to inspect the size and shape of a numpy array?**

This section contains attributes that can be used with a numpy array namely *shape*, *dtype*, *size*, *ndim*, *itemsize*

In [11]:
# Create a 2d array with 3 rows and 4 columns
list2 = [[1, 2, 3, 4], [3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype = int)  # Don't use deprecated dtype
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [12]:
# Uses of attributes associated with numpy array

# shape
print("Shape:", arr2.shape)

# dtype
print("Datatype:", arr2.dtype)

# size
print("Size:", arr2.size)

# ndim
print("Num Dimensions:", arr2.ndim)

# itemsize
print("Size of each item:", arr2.itemsize)

Shape: (3, 4)
Datatype: int64
Size: 12
Num Dimensions: 2
Size of each item: 8


<br><br>
## **4. How to extract specific items from an array?**

In [13]:
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [14]:
# Extract the first 2 rows and columns
arr2[:2, :2]    # Similar to what we do with Python list
# list2[:2, :2]    # Creates error

array([[1, 2],
       [3, 4]])

#### Super important to understand the difference between slicing and indexing. Below scripts contains just that.

In [15]:
print(arr2[2,])
print(arr2[2:3,])

[5 6 7 8]
[[5 6 7 8]]


In [16]:
# The type may look same but the dimensions vary
print("Indexing Type:", type(arr2[2]), "\t\tIndexing dimension:", arr2[2].ndim)
print("Indexing Type:", type(arr2[2:3]), "\t\tSlicing dimension:", arr2[2:3].ndim)

Indexing Type: <class 'numpy.ndarray'> 		Indexing dimension: 1
Indexing Type: <class 'numpy.ndarray'> 		Slicing dimension: 2


In [17]:
# Becomes more clear with 1 dimensional arrays

# Creates 1d array
example_array1d = np.array([5, 9, 2, 6, 1, 6])
print("Slicing:", example_array1d[:1], "\t\t\tIndexing:", example_array1d[0])
print("Slicing dimension:", example_array1d[:1].ndim, "\t\tIndexing dimension:", example_array1d[0].ndim)
print("Slicing type:", type(example_array1d[:1]), "\tIndexing type:", type(example_array1d[0]))

Slicing: [5] 			Indexing: 5
Slicing dimension: 1 		Indexing dimension: 0
Slicing type: <class 'numpy.ndarray'> 	Indexing type: <class 'numpy.int64'>


<br><br>

In [18]:
# Get the boolean output by applying the condition to each element
b = arr2 > 4
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [19]:
# Extracts only the elements that are greater than 4
arr2[b]

array([5, 6, 5, 6, 7, 8])

# 
### **4.1 How to reverse the rows and the whole array?**

In [20]:
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [21]:
# Reverse only the row position
arr2[::-1, ]    # Can be written as arr2[::-1]

array([[5, 6, 7, 8],
       [3, 4, 5, 6],
       [1, 2, 3, 4]])

In [22]:
# Reverse only the column position
arr2[:, ::-1]

array([[4, 3, 2, 1],
       [6, 5, 4, 3],
       [8, 7, 6, 5]])

In [23]:
# Reverse the row and column position
arr2[::-1, ::-1]

array([[8, 7, 6, 5],
       [6, 5, 4, 3],
       [4, 3, 2, 1]])

<br> 
### **4.2 How to represent missing values and infinite?**

In [24]:
# Insert a nan and an inf
#arr2[1, 1] = np.nan    # not a number
#arr2[2, 2] = np.inf    # infinite
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [25]:
# Replace nan and inf with -1. Don't use arr2 == np.nan
missing_bool = np.isnan(arr2) | np.isinf(arr2)
arr2[missing_bool] = -1
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

<br> 
### **4.3 How to compute mean, min, max on the ndarray?**

In [26]:
# mean, max and min
print("Mean value is:", arr2.mean())
print("Max value is:", arr2.max())
print("Min value is:", arr2.min())

Mean value is: 4.5
Max value is: 8
Min value is: 1


In [27]:
# Row wise and column wise min
print("Column wise minimum:", np.amin(arr2, axis = 0))
print("Row wise minimum:", np.amin(arr2, axis = 1))

Column wise minimum: [1 2 3 4]
Row wise minimum: [1 3 5]


In [28]:
# Cumulative Sum
arr2.cumsum()

array([ 1,  3,  6, 10, 13, 17, 22, 28, 33, 39, 46, 54])

<br><br>
## **Just a self practise of** *apply_over_axes()*
#### A little difficult to get your head around in the first go. Some knowledge of matrix might be really helpful.

In [29]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [30]:
a.shape

(2, 3, 4)

In [31]:
np.apply_over_axes(np.sum, a, [0,2])

array([[[ 60],
        [ 92],
        [124]]])

<br><br>
## **5. How to create a new array from an existing array?**

*If you just assign a portion of an array to another array, the new array you just created refers to the parent array in memory.*<br>
*That means, if you make any changes to the new array, it will reflect in the parent array as well.*</br>

In [32]:
# Assign portion of arr2 to arr2a. Doesn't really create a new array.
arr2a = arr2[:2, :2]
arr2a[:1, :1] = 10    # 100 will reflect in arr2
arr2

array([[10,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 5,  6,  7,  8]])

In [33]:
# Copy a portion of arr2 to arr2b
arr2b = arr2[:2, :2].copy()
arr2b[:1, :1] = 126
arr2

array([[10,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 5,  6,  7,  8]])

<br><br>
## **6. Reshaping and Flattening Multidimensional arrays**

In [34]:
# Reshape a 3X4 array to 4X3 array
arr2.reshape(4, 3)

array([[10,  2,  3],
       [ 4,  3,  4],
       [ 5,  6,  5],
       [ 6,  7,  8]])

<br> 
### **6.1 What is the difference between flatten() and ravel()?**
flatten() creates a copy of the parent array and transforms it into 1-d array whereas ravel() creates a reference to parent array and transforms it into 1-d array.

In [35]:
# Flatten it to a 1d array
arr2.flatten()

array([10,  2,  3,  4,  3,  4,  5,  6,  5,  6,  7,  8])

In [36]:
# Changing the flattened array does not change parent
b1 = arr2.flatten()
b1[0] = 85
arr2

array([[10,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 5,  6,  7,  8]])

In [37]:
# Changing the raveled array changes the parent also.
b2 = arr2.ravel()
b2[0] = 85
arr2

array([[85,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 5,  6,  7,  8]])

<br><br> 
## **7. How to create sequences, repetitions and random numbers using numpy?**

In [38]:
# Lower limit is 0 to be default
print(np.arange(10))

# 0 to 15
print(np.arange(0, 15))

# 0 to 9 with step of 2
print(np.arange(0, 9, 2))

# 10 to 1, decreasing order
print(np.arange(10, 0, -1))

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0 2 4 6 8]
[10  9  8  7  6  5  4  3  2  1]


In [39]:
# Create a numpy array with custom number of items between start and end

# Start with 1 and end at 50
np.linspace(start = 1, stop = 50, num = 10, dtype = int)   # Creates 64 bit int by default

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

In [40]:
# Limit the number of digits after decimal to 2
np.set_printoptions(precision = 2)

# Start at 10^1 and end at 10^50
np.logspace(start=1, stop=50, num=10, base=10)

array([1.00e+01, 2.78e+06, 7.74e+11, 2.15e+17, 5.99e+22, 1.67e+28,
       4.64e+33, 1.29e+39, 3.59e+44, 1.00e+50])

In [41]:
# Creates multidimensional array containing all zeros
np.zeros([2, 2])

array([[0., 0.],
       [0., 0.]])

In [42]:
# Create multidimensional array containing all ones
np.ones([5, 2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

 
### **7.1 How to create repeating sequences?**

In [43]:
a = [1, 2, 3]

# Repeat whole of 'a' two times
print('Tile:', np.tile(a, 2))

# Repeat each element of 'a' two times
print('Repeat:', np.repeat(a, 2)) 

Tile: [1 2 3 1 2 3]
Repeat: [1 1 2 2 3 3]


<br><br> 
#### **Doing a little more with tile() method. Some knowledge of matrices and ndarray attributes in general will be a very useful aid.**
Let,
$$A =
 \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
 \end{bmatrix}$$

<br>For example,<br>
$$>>>np.tile(A, (3,2))$$
While performing tile( ), think of the whole array as a single element and create a matrix of the shape as specified in the function with each element as the matrix itself.
$$
 \begin{bmatrix}
  A & A & A \\
  A & A & A \\
 \end{bmatrix}$$

<br> Replace each A as,
$$ 
\begin{bmatrix}
 \begin{bmatrix}
         1 & 2 & 3 \\
         4 & 5 & 6 \\
  \end{bmatrix}
 & 
 \begin{bmatrix}
         1 & 2 & 3 \\
         4 & 5 & 6 \\
  \end{bmatrix}
   \\
 \begin{bmatrix}
         1 & 2 & 3 \\
         4 & 5 & 6 \\
  \end{bmatrix}
 & 
 \begin{bmatrix}
         1 & 2 & 3 \\
         4 & 5 & 6 \\
  \end{bmatrix}
\\
 \begin{bmatrix}
         1 & 2 & 3 \\
         4 & 5 & 6 \\
  \end{bmatrix}
 & 
 \begin{bmatrix}
         1 & 2 & 3 \\
         4 & 5 & 6 \\
  \end{bmatrix}
 \\
\end{bmatrix}
$$ 

Remove the inside brackets.<br>
$$
\begin{bmatrix}
    1 & 2 & 3 & 1 & 2 & 3 \\
    4 & 5 & 6 & 4 & 5 & 6 \\
    1 & 2 & 3 & 1 & 2 & 3 \\
    4 & 5 & 6 & 4 & 5 & 6 \\
    1 & 2 & 3 & 1 & 2 & 3 \\
    4 & 5 & 6 & 4 & 5 & 6 \\
\end{bmatrix}
$$
<br>
**Note: The dimension of the matrix doesn't change.**<br>
*Refer to the documentation of tile() method for more help.*

In [44]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.tile(b, (3, 2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [46]:
a = np.array([0, 1, 2])
a

array([0, 1, 2])

In [47]:
np.tile(a, (2, 1))

array([[0, 1, 2],
       [0, 1, 2]])

### **7.2 How to generate random numbers?**

In [48]:
# Random numbers between [0, 1) of shape 2, 2
print(np.random.rand(2, 2))

# Normal distribution with mean = 0 and variance = 1 of shape 2, 2
print(np.random.randn(2, 2))

# Random integers between [0, 10) of shape 2, 2
print(np.random.randint(0, 10, size = [2, 2]))

# One random number between [0, 1)
print(np.random.random())

# Random number between [0, 1) of shape 2, 2
print(np.random.random(size = [2, 2]))

# Pick 10 items from a given list with equal probability
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size = 10))

# Pick 10 items from a given list with a predefined probability
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size = 10, p = [0.3, 0.2, 0.1, 0.2, 0.2]))


[[0.39 0.  ]
 [0.18 0.55]]
[[ 1.62  1.11]
 [ 1.12 -2.41]]
[[9 4]
 [3 1]]
0.8869637804261532
[[0.44 0.6 ]
 [0.52 0.27]]
['e' 'o' 'o' 'i' 'a' 'u' 'i' 'o' 'e' 'u']
['e' 'e' 'e' 'o' 'u' 'u' 'i' 'a' 'e' 'a']


In [49]:
# Create the random state
rn = np.random.RandomState(100)

# Create random numbers between [0, 1) of shape 2, 2
print(rn.rand(2, 2))

[[0.54 0.28]
 [0.42 0.84]]


In [50]:
# Set the random seed
np.random.seed(100)

# Create random numbers between [0, 1) of shape 2, 2
print(np.random.rand(2, 2))

[[0.54 0.28]
 [0.42 0.84]]



### **7.3 How to get the unique items and the counts?**

In [51]:
# Create random integers of size 10 between [0, 10)
np.random.seed(100)
arr_rand = np.random.randint(0, 10, size = 10)
print(arr_rand)

[8 8 3 7 7 0 4 2 5 2]


In [52]:
# Get the unique items and their counts
uniq, counts = np.unique(arr_rand, return_counts = True)
print('Unique items : ', uniq)
print('Counts       : ', counts)

Unique items :  [0 2 3 4 5 7 8]
Counts       :  [1 2 1 1 1 2 2]
